USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE SCD1_DB;

CREATE OR REPLACE STORAGE INTEGRATION SCD1_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'Your_scd1_role_arn_from_aws'
  STORAGE_ALLOWED_LOCATIONS = ('Your_S3_URI_of_data_bucket_with_folder');

DESC INTEGRATION SCD1_INT;

CREATE OR REPLACE STAGE SCD1_DB.PUBLIC.SCD1_STAGE
STORAGE_INTEGRATION = SCD1_INT
URL= 'Your_S3_URI_of_data_bucket_with_folder';

ls @SCD1_DB.PUBLIC.SCD1_STAGE;
